package patrol

type ApiGroup struct {
	// Code generated by github.com/oldweipro/gin-admin Begin; DO NOT EDIT.

	PatrolItemApi
	PatrolTaskApi
	PatrolSiteApi
	IdentityApi
	AccountApi
	CertificationRecordApi
	PersonnelApi
	// Code generated by github.com/oldweipro/gin-admin End; DO NOT EDIT.
}
