package patrol

type RouterGroup struct {
	// Code generated by github.com/oldweipro/gin-admin Begin; DO NOT EDIT.

	PatrolItemRouter
	PatrolTaskRouter
	PatrolSiteRouter
	IdentityRouter
	AccountRouter
	CertificationRecordRouter
	PersonnelRouter
	// Code generated by github.com/oldweipro/gin-admin End; DO NOT EDIT.
}
