package patrol

type ServiceGroup struct {
	// Code generated by github.com/oldweipro/gin-admin Begin; DO NOT EDIT.

	PatrolItemService
	PatrolTaskService
	PatrolSiteService
	IdentityService
	AccountService
	CertificationRecordService
	PersonnelService
	// Code generated by github.com/oldweipro/gin-admin End; DO NOT EDIT.
}
